// Generated by gencpp from file triangulator/triangulatorCommandResponse.msg
// DO NOT EDIT!


#ifndef TRIANGULATOR_MESSAGE_TRIANGULATORCOMMANDRESPONSE_H
#define TRIANGULATOR_MESSAGE_TRIANGULATORCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <triangulator/beaconCommand.h>

namespace triangulator
{
template <class ContainerAllocator>
struct triangulatorCommandResponse_
{
  typedef triangulatorCommandResponse_<ContainerAllocator> Type;

  triangulatorCommandResponse_()
    : triResponseCommand()  {
    }
  triangulatorCommandResponse_(const ContainerAllocator& _alloc)
    : triResponseCommand(_alloc)  {
    }



   typedef  ::triangulator::beaconCommand_<ContainerAllocator>  _triResponseCommand_type;
  _triResponseCommand_type triResponseCommand;




  typedef boost::shared_ptr< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct triangulatorCommandResponse_

typedef ::triangulator::triangulatorCommandResponse_<std::allocator<void> > triangulatorCommandResponse;

typedef boost::shared_ptr< ::triangulator::triangulatorCommandResponse > triangulatorCommandResponsePtr;
typedef boost::shared_ptr< ::triangulator::triangulatorCommandResponse const> triangulatorCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::triangulator::triangulatorCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace triangulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'triangulator': ['/Users/GBrill/catkin_ws/src/triangulator_service/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "571fa54aeddefe86925e046d37b0781b";
  }

  static const char* value(const ::triangulator::triangulatorCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x571fa54aeddefe86ULL;
  static const uint64_t static_value2 = 0x925e046d37b0781bULL;
};

template<class ContainerAllocator>
struct DataType< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "triangulator/triangulatorCommandResponse";
  }

  static const char* value(const ::triangulator::triangulatorCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beaconCommand triResponseCommand\n\
\n\
================================================================================\n\
MSG: triangulator/beaconCommand\n\
uint32 commandID\n\
uint32 returnCode\n\
string commandMessage\n\
float32[] floatArgs\n\
int32[] intArgs\n\
string[] stringArgs\n\
beaconSettings bSettings\n\
beaconBest[] bBeaconBest\n\
float32[6] envLimits\n\
================================================================================\n\
MSG: triangulator/beaconSettings\n\
beaconSetting[] beaconValues\n\
\n\
================================================================================\n\
MSG: triangulator/beaconSetting\n\
float32 beaconID\n\
string beaconName\n\
float32 X\n\
float32 Y\n\
float32 Z\n\
\n\
================================================================================\n\
MSG: triangulator/beaconBest\n\
float32 ID\n\
float32 R\n\
float32 C\n\
float32 SS\n\
float32 Theta\n\
float32 Phi\n\
float32 AdjR\n\
float32 AdjC\n\
float32 ObsErr\n\
float32 Status\n\
bool IsReflect\n\
bool IsUsedInEst\n\
bool IsOvl\n\
";
  }

  static const char* value(const ::triangulator::triangulatorCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.triResponseCommand);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct triangulatorCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::triangulator::triangulatorCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::triangulator::triangulatorCommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "triResponseCommand: ";
    s << std::endl;
    Printer< ::triangulator::beaconCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.triResponseCommand);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRIANGULATOR_MESSAGE_TRIANGULATORCOMMANDRESPONSE_H
